### ISSUE TITLE
A bunch of errors

### ISSUE THREAD

**Issue by Atulin** [Akaisorani/pixiv-crawler#2]
```ps
PS C:\Users\Angius> py pixiv.py
Traceback (most recent call last):
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixiv.py", line 9, in <module>
    pc.login()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pixiv_crawler\scraper_manga.py", line 50, in login
    r=session_requests.get(pixiv_root)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Code I'm trying to execute:
```python
import pixiv_crawler as pc

pc.set_value('username','Username')
pc.set_value('password','Password')
pc.set_value("local_save_root","./pixiv/%y.%m.%d")
pc.set_value("cookies_file","./pixiv/cookies.txt")
pc.set_value("garage_file","./pixiv/garage.txt")
pc.login()

pc.dl_artist(15039870,pic_num=-1,deep_into_manga=True)
```

Python 3.6.5, Win10

**Comment by Akaisorani** [comment]
@Atulin 
Thanks for your reporting.
I ran your code but got no errors like the above, everything is ok.
It seems the problem is related to the network part. Make sure you have installed the **latest** `requests` package. (https://pypi.org/project/requests/)
Looking forward to more error information from you.

**Comment by Atulin** [comment]
Turns out, I have ``requests`` installed already:

```ps
PS C:\Users\Angius> pip install requests
Requirement already satisfied: requests in c:\users\angius\appdata\local\programs\python\python36-32\lib\site-packages (2.18.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\angius\appdata\local\programs\python\python36-32\lib\site-packages (from requests) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\angius\appdata\local\programs\python\python36-32\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\angius\appdata\local\programs\python\python36-32\lib\site-packages (from requests) (2018.4.16)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\angius\appdata\local\programs\python\python36-32\lib\site-packages (from requests) (1.22)
```

```ps
PS C:\Users\Angius> py pixiv.py
Traceback (most recent call last):
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixiv.py", line 9, in <module>
    pc.login()
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pixiv_crawler\scraper_manga.py", line 50, in login
    r=session_requests.get(pixiv_root)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Angius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by Akaisorani** [comment]
@Atulin 
The error shows that the pixiv server closed your connection.
If you are running your code on a remote ECS(Elastic Compute Service), then check whether its IP is banned by pixiv.
If you are running your code on your own computer, then check whether you can open pixiv in your browser.

**Comment by Atulin** [comment]
I'm running it on my own computer, and I can access Pixiv's website perfectly fine.

**Comment by Atulin** [comment]
Update: most probably solved. Pixiv has me log in with **email** and password, not **login** and password for some reason. I'll test it again when I'm home.
