### ISSUE TITLE
Can't run properly

### ISSUE THREAD

**Issue by Insanecamo** [Akaisorani/pixiv-crawler#5]
When I run this code:
```py
import pixiv_crawler as pc

pc.set_value('username','(my user)')
pc.set_value('password','(my password')
pc.set_value("local_save_root","./%y.%m.%d")
pc.set_value("chrome","chromedriver.exe")
pc.login()
pc.dl_tag('線画', 20)
```
I get thrown this
```
loaded cookies
https://www.pixiv.net/en/tags/%E7%B7%9A%E7%94%BB/artworks?p=1
Traceback (most recent call last):
  File "C:\Users\insan\anaconda3\lib\site-packages\pixiv_crawler\scraper_manga.py", line 230, in get_master_imagelist_from_resp
    retlist=gmifr_tag(r)
  File "C:\Users\insan\anaconda3\lib\site-packages\pixiv_crawler\scraper_manga.py", line 213, in gmifr_tag
    js=r.json()
  File "C:\Users\insan\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\insan\anaconda3\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\insan\anaconda3\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\insan\anaconda3\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I've tried to figure out the issue, but I'm unable to get it.
Python 3.7 win10

**Comment by Akaisorani** [comment]
It works for me. I got this:
```
loaded cookies
https://www.pixiv.net/tags/%E7%B7%9A%E7%94%BB/artworks?p=1
<https://i.pximg.net/img-original/img/2014/05/19/13/05/41/43592297_p0.png>
Thread-1 is downloading ./temp/20.06.27/tag-線画/43592297_p0.png
<https://i.pximg.net/img-original/img/2014/09/30/22/07/32/31359662_p0.png>
Thread-2 is downloading ./temp/20.06.27/tag-線画/31359662_p0.png
<https://i.pximg.net/img-original/img/2018/12/19/17/37/14/72183715_p0.jpg>
......
```

This error `simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` is caused by empty json content or wrong json format.
Make sure your program can access pixiv website properly (means if you have been banned, you may need a proxy).

Please test other functions and report more information.
Thanks.

**Comment by Insanecamo** [comment]
I've tried all the other download functions, and every other one works. I've tried changing the num_deep and the tag used in the call, and I get thrown the same error.

**Comment by Akaisorani** [comment]
I think I have figured out the problem.
The right ajax query address is 
`https://www.pixiv.net/ajax/search/artworks/%E7%B7%9A%E7%94%BB/?p=1`
instead of 
`https://www.pixiv.net/`**en**`/ajax/search/artworks/%E7%B7%9A%E7%94%BB/?p=1`

Thanks for your report, I will fix this today.

**Comment by Akaisorani** [comment]
@Insanecamo Fixed. Have fun!
